<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" referrerpolicy="no-referrer" />
    <title>Avatar Genetaror</title>
</head>
<body>
    <h1 class="mainContent">Avatar Generator</h1>
    <div id="flash" class="mainContent"></div>

    <div class="mainContent">
        <div id="avatarsvg">
            <?= $svg; ?>
        </div>
        <div>
            <form action="index.php" method="POST" class="GenerateForm">
            <input type="hidden" name="action" value="generate">
                <div>
                    <label for="size">Selectionnez la taille</label></br>
                    <select name="size" id="size">
                        <?php for($i=1; $i<30; $i++): ?>
                            <option <?= $i==$size ? 'selected' : '';?> value="<?=$i;?>"><?=$i;?></option>
                        <?php endfor; ?>
                    </select>
                </div>
                <div>
                    <label for="color">Selectionnez le nombre de couleurs</label></br>
                    <select name="color" id="color">
                        <?php for($i=1; $i<30; $i++): ?>
                            <option <?= $i==$color ? 'selected' : '';?> value="<?=$i;?>"><?=$i;?></option>
                        <?php endfor; ?>
                    </select>
                </div> 
                    <input class="submit" type="submit" value="Générer">
            </form>
        </div>
        <div class="save">
            <form action="index.php" method="POST" class="saveForm" id="formSave">
                <input type="hidden" name="svg" value="<?= htmlspecialchars($svg); ?>">
                <input class="submit" type="submit" value="Enregistrer">
                <input type="hidden" name="action" value="save">
                <input type="hidden" name="size" value="<?=$size;?>">
                <input type="hidden" name="color" value="<?=$color;?>">
            </form>
        </div>
        <div class="download">
            <form action="index.php" method="POST">
                <input type="hidden" name="svg" value="<?= htmlspecialchars($svg); ?>">
                <input class="submit" type="submit" value="Telecharger">
                <input type="hidden" name="action" value="download">
            </form>
        </div>
    </div>

    <script src="js/app.js"></script>
        
</body>
</html>